#!/bin/bash
CURR=`cat /sys/class/backlight/intel_backlight/brightness`
MAX=`cat /sys/class/backlight/intel_backlight/max_brightness`
NEW=$(($CURR+20))
if [ $NEW -gt $MAX ]
  then
    NEW=$MAX
fi
echo $NEW | sudo /usr/bin/tee /sys/class/backlight/intel_backlight/brightness
