#!/bin/bash
CURR=$(</sys/class/backlight/intel_backlight/brightness)
MIN=0
MAX=$(</sys/class/backlight/intel_backlight/max_brightness)
NEW=$((CURR-20))
if [[ $NEW -lt $MIN ]]
  then
    NEW=$MIN
fi
echo $NEW | sudo /usr/bin/tee /sys/class/backlight/intel_backlight/brightness
